// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEbJ4rxhFfO6cJKSspLigdFkAcF1yh8l0',
    appId: '1:1013901044498:web:354eda5bf29678b8eaa1cb',
    messagingSenderId: '1013901044498',
    projectId: 'makka-road',
    authDomain: 'makka-road.firebaseapp.com',
    storageBucket: 'makka-road.firebasestorage.app',
    measurementId: 'G-FV6JJM9W8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLaO_RxICkoWSQpFzuqh3zLs2c5gtIgk',
    appId: '1:1013901044498:android:1eeb6134cd29d55beaa1cb',
    messagingSenderId: '1013901044498',
    projectId: 'makka-road',
    storageBucket: 'makka-road.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4VTSRgGRvOCsUs6VNKpIjxDIgFdMbZcA',
    appId: '1:1013901044498:ios:7253303ce799fd3deaa1cb',
    messagingSenderId: '1013901044498',
    projectId: 'makka-road',
    storageBucket: 'makka-road.firebasestorage.app',
    iosBundleId: 'com.example.makkaRoad',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4VTSRgGRvOCsUs6VNKpIjxDIgFdMbZcA',
    appId: '1:1013901044498:ios:7253303ce799fd3deaa1cb',
    messagingSenderId: '1013901044498',
    projectId: 'makka-road',
    storageBucket: 'makka-road.firebasestorage.app',
    iosBundleId: 'com.example.makkaRoad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEbJ4rxhFfO6cJKSspLigdFkAcF1yh8l0',
    appId: '1:1013901044498:web:d81be49429cd2e4eeaa1cb',
    messagingSenderId: '1013901044498',
    projectId: 'makka-road',
    authDomain: 'makka-road.firebaseapp.com',
    storageBucket: 'makka-road.firebasestorage.app',
    measurementId: 'G-M8EX9ME8LG',
  );
}
